spring.application.name=security-complete-demo

# ==========================================
# Application
# ==========================================

# ==========================================
# Oracle Database
# ==========================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=sys as sysdba
spring.datasource.password=password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ==========================================
# JPA / Hibernate
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# Oracle Dialect (Optional in Hibernate 6+)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# ==========================================
# Hikari Connection Pool
# ==========================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# ==========================================
# Logging
# ==========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================================
# JWT
# ==========================================
jwt.secret=3WAZj7n3s7A1i+1FCQ+QkTnRcbOq2kG+TnY7G4OQ4sH1N6v7d6k9d1Kk7N1L2QxV
jwt.expiration=3600000

spring.main.allow-circular-references=true

