spring.application.name=product-api

spring.datasource.url=jdbc:h2:file:./data/productdb
#spring.datasource.driverClassName=org.h2.Driver



# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=sa
spring.datasource.password=

# Show SQL in console
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# ==========================
# H2 Console
# ==========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================
# Server
# ==========================

# ==========================
# Logging (Optional)
# ==========================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
